Changes to work with autodoc files

diff --git a/manpages/convert b/manpages/convert
--- a/manpages/convert
+++ b/manpages/convert
@@ -1,8 +1,26 @@
 #!/bin/csh -f
+#
+# Script to convert .preman files to .man files, and .man files to .1 files
+# then to .html files,
+#
+#  $Author$
+#
+#  $Date$
+#
+#  $Revision$
+#
+#  $Log$
+#  Revision 3.1  2003/10/08 17:17:43  mast
+#  Changes to work with autodoc files
 
 set version = `cat ../.version`
+set instext = "INSERT OPTION"
 
-which nroff
+set prelist = `\find . -type f -name '*.preman'`
+
+if ($argv[1] == "clean") goto clean
+
+which nroff >& /dev/null
 if ($status) then
     echo nroff not on path
     exit 1
@@ -13,9 +31,29 @@ set copt = "-c"
 echo junk | nroff -c >& /dev/null
 if ($status) set copt = ""
 
+@ ind = 1
+while ($ind <= $#prelist)
+    set i = $prelist[$ind]
+    set manout = ${i:r}.man
+    grep "$instext" $i >& /dev/null
+    if ($status) then
+        echo "$instext, the keyword for text to be replaced, is missing in $i"
+        exit 1
+    endif
+    echo "converting $i to $manout"
+    awk "NR==1, /$instext/" $i | grep -v "$instext" >! $manout
+    $argv[1]/autodoc2man 1 1 ${i:r} >> $manout
+    if ($status) then
+        echo "Error getting manpage text from option file for ${i:r}"
+        exit 1
+    endif
+    awk "/$instext/, /GobbledyGook/" $i | grep -v "$instext" >> $manout
+    @ ind++
+end    
+
 foreach i (*.man)
-	echo "converting $i to ${i:r}.1"
-	sed "/^\.TH/s/ [0-9]\.[0-9\.]* / $version /" $i | nroff -man $copt >! ${i:r}.1
+    echo "converting $i to ${i:r}.1"
+    sed "/^\.TH/s/ [0-9]\.[0-9\.]* / $version /" $i | nroff -man $copt >! ${i:r}.1
 end
 
 foreach j (*.1)
@@ -23,6 +61,12 @@ foreach j (*.1)
 	$argv[1]/mantohtml < $j >! ${j:r}.html
 end
 
+clean:
+@ ind = 1
+while ($ind <= $#prelist)
+    \rm -f ${prelist[$ind]:r}.man
+    @ ind++
+end
 
 exit
 
