Ridiculous retry on mt

diff --git a/installqtlib b/installqtlib
--- a/installqtlib
+++ b/installqtlib
@@ -179,12 +179,19 @@ if ($qtlibdir == "bin") then
         foreach i ($instdir/bin/*.exe)
             if ("$i:t" != $assistname) then
                 set icyg = `cygpath -w $i`
-                mt "-outputresource:$icyg;#1" -manifest $manifest > /dev/null
-                if ($status) then
-                    \echo "Error running: mt -outputresource:$icyg;#1 -manifest $manifest"
-                    mt "-outputresource:$icyg;#1" -manifest $manifest
-                    exit 1
-                endif
+                @ count = 0
+                while ($count < 5)
+                    @ count++
+                    set errout = `mt "-outputresource:$icyg;#1" -manifest $manifest`
+                    if (! $status) then
+                        break
+                    else 
+                        \echo "Error running: mt -outputresource:$icyg;#1 -manifest $manifest"
+                        echo errout
+                        if ($count >= 5) exit 1
+                        echo "Try again..."
+                    endif
+                end
             endif
         end
     endif
@@ -208,6 +215,9 @@ exit 0
 
 #
 #  $Log$
+#  Revision 3.37  2009/03/16 22:18:15  mast
+#  Escape echo so it works with c: stuff
+#
 #  Revision 3.36  2009/03/14 15:39:58  mast
 #  Fixed missing endif
 #
