No no those really were errors, back to normal single error processing on mt

diff --git a/installqtlib b/installqtlib
--- a/installqtlib
+++ b/installqtlib
@@ -179,19 +179,13 @@ if ($qtlibdir == "bin") then
         foreach i ($instdir/bin/*.exe)
             if ("$i:t" != $assistname) then
                 set icyg = `cygpath -w $i`
-                @ count = 0
-                while ($count < 5)
-                    @ count++
-                    set errout = `mt "-outputresource:$icyg;#1" -manifest $manifest`
-                    if ((! $status) || $status == 79) then
-                        break
-                    else 
-                        \echo "Error running: mt -outputresource:$icyg;#1 -manifest $manifest"
-                        echo "$errout"
-                        if ($count >= 5) exit 1
-                        echo "Try again..."
-                    endif
-                end
+                set errout = `mt "-outputresource:$icyg;#1" -manifest $manifest`
+                set errstat = $status
+                if ($errstat) then
+                    \echo "Error code $errstat running: mt -outputresource:$icyg;#1 -manifest $manifest"
+                    echo "$errout"
+                    exit 1
+                endif
             endif
         end
     endif
@@ -215,6 +209,9 @@ exit 0
 
 #
 #  $Log$
+#  Revision 3.40  2009/03/17 04:00:23  mast
+#  Allow exit status 79 on mt, it is what we get now!
+#
 #  Revision 3.39  2009/03/17 02:24:52  mast
 #  Try again to get error message
 #
