Added Qt assistant and library if needed

diff --git a/installqtlib b/installqtlib
--- a/installqtlib
+++ b/installqtlib
@@ -1,58 +1,13 @@
 #!/bin/csh -f
-# Script to add Qt libraries and links to a distribution file
+# Script to add Qt libraries and links to a distribution file, and copy other
+# files as needed for particular system
 #
 #  $Author$
 #
 #  $Date$
 #
 #  $Revision$
-#
-#  $Log$
-#  Revision 3.19  2004/04/03 20:01:00  mast
-#  Added ability to copy install files and rename them
-#
-#  Revision 3.18  2004/01/27 05:53:54  mast
-#  Needed to define LIBEXT line better
-#
-#  Revision 3.17  2004/01/27 05:16:26  mast
-#  Start out by copying needed files from dist
-#
-#  Revision 3.16  2003/12/30 17:24:58  mast
-#  Delete stray .libs in windows install
-#
-#  Revision 3.15  2003/12/02 02:07:08  mast
-#  Change the way Qt lib is identified in Windows, give up on Makefiles
-#
-#  Revision 3.14  2003/11/26 21:48:08  mast
-#  Allow large number of dll lists to copy
-#
-#  Revision 3.13  2003/10/25 16:25:59  mast
-#  fix for Cygwin/Intel and add ability to copy other libraries
-#
-#  Revision 3.12  2003/10/25 02:52:27  mast
-#  find library in cygwin/Intel makefile
-#
-#  Revision 3.11  2003/10/03 05:04:45  mast
-#  Discovered extension can go before (SGI) or after (Mac) version numbers
-#
-#  Revision 3.10  2003/09/25 00:04:08  mast
-#  Improve test for no entry in configure
-#
-#  Revision 3.9  2003/08/25 18:47:13  mast
-#  Have it make the install directory if needed, and delete existing links
-#
-#  Revision 3.8  2003/08/13 20:01:41  mast
-#  Have it use LIBEXT from configure if available, add test for libqt.la
-#
-#  Revision 3.7  2003/05/08 23:29:09  mast
-#  change for windows
-#
-#  Revision 3.6  2003/05/08 21:42:35  mast
-#  Get libqt name better
-#
-#  Revision 3.5  2003/05/08 20:58:43  mast
-#  Initial creation (deleted messages while thrashing
-#
+#  Log at end of file
 #
 
 # get the install directory
@@ -111,6 +66,16 @@ while ($dllnum < 100)
 end
 
 #
+# Copy Qt assistant which could be an exe or a .app directory
+#
+if (`\find $QTDIR/bin -name 'assistant*' -print` != "") then
+    \cp -r $QTDIR/bin/assistant* $instdir/$qtlibdir
+else
+    echo "Qt Assistant not found in $QTDIR/bin"
+    exit 1
+endif
+
+#
 # grab the name of the Qt lib from the ever-useful sendevent Makefile
 #
 set qtlib = `sed -n '/^LIBS.*=/s/^.*-lqt/libqt/p' sendevent/Makefile`
@@ -133,44 +98,108 @@ if ($qtlibdir == "bin") then
 
     # 6/25/04: discovered these were not coming through right, and it matters
     #
-    chmod a+rx $instdir/$qtlibdir/*.dll
+    chmod a+rx $instdir/$qtlibdir/*.dll $instdir/$qtlibdir/assistant*
     exit 0
 endif
 
 set qtlib = $qtlib[1]
 
 #
-# Count up non-links and save name of real file
+# For qt lib and possible assistant lib, count up non-links and save name of 
+# real file
 #
-@ numreal = 0
-foreach i ($QTDIR/lib/${qtlib}.*${libext}*)
-    if ((! -l $i) && $i:e != "prl" && $i:e != "la") then
-        @ numreal++
-        set realname = $i
-    endif
-end
+@ whichlib = 0
+while ($whichlib < 2)
+    @ numreal = 0
+    foreach i ($QTDIR/lib/${qtlib}.*${libext}*)
+        if ((! -l $i) && $i:e != "prl" && $i:e != "la") then
+            @ numreal++
+            set realname = $i
+        endif
+    end
 
-if ($numreal == 0) then
+    if ($numreal == 0) then
+        if ($whichlib > 0) break
         echo "installqtlib: Qt Library not found at $QTDIR/lib/$qtlib.*"
         exit 1
-endif
-
-if ($numreal > 1) then
-    echo "installqtlib: $numreal real Qt libraries match $QTDIR/lib/$qtlib.*"
-    echo Cannot make links properly
-    exit 1
-endif
-
-#
-# Make directory, copy the real file, make the links
-#
-if (! -e $instdir/$qtlibdir) mkdir -p $instdir/$qtlibdir
-
-cd $instdir/$qtlibdir
-\cp $realname .
-foreach i ($QTDIR/lib/${qtlib}*${libext}*)
-    if (-l $i) then
-        \rm -f $i:t
-        ln -s $realname:t $i:t
     endif
+
+    if ($numreal > 1) then
+        echo "installqtlib: $numreal real Qt libraries match $QTDIR/lib/$qtlib.*"
+        echo Cannot make links properly
+        exit 1
+    endif
+
+    #
+    # Make directory, copy the real file, make the links
+    #
+    if (! -e $instdir/$qtlibdir) mkdir -p $instdir/$qtlibdir
+
+    cd $instdir/$qtlibdir
+    \cp $realname .
+    foreach i ($QTDIR/lib/${qtlib}*${libext}*)
+        if (-l $i) then
+            \rm -f $i:t
+            ln -s $realname:t $i:t
+        endif
+    end
+
+    #
+    # Copy libqassistantclient the same way if it is a shared lib
+    #
+    set qtlib = libqassistantclient
+    @ whichlib++
 end
+exit 0
+
+#
+#  $Log$
+#  Revision 3.20  2004/06/26 02:46:51  mast
+#  Needed to make all DLLs read/execute by all
+#
+#  Revision 3.19  2004/04/03 20:01:00  mast
+#  Added ability to copy install files and rename them
+#
+#  Revision 3.18  2004/01/27 05:53:54  mast
+#  Needed to define LIBEXT line better
+#
+#  Revision 3.17  2004/01/27 05:16:26  mast
+#  Start out by copying needed files from dist
+#
+#  Revision 3.16  2003/12/30 17:24:58  mast
+#  Delete stray .libs in windows install
+#
+#  Revision 3.15  2003/12/02 02:07:08  mast
+#  Change the way Qt lib is identified in Windows, give up on Makefiles
+#
+#  Revision 3.14  2003/11/26 21:48:08  mast
+#  Allow large number of dll lists to copy
+#
+#  Revision 3.13  2003/10/25 16:25:59  mast
+#  fix for Cygwin/Intel and add ability to copy other libraries
+#
+#  Revision 3.12  2003/10/25 02:52:27  mast
+#  find library in cygwin/Intel makefile
+#
+#  Revision 3.11  2003/10/03 05:04:45  mast
+#  Discovered extension can go before (SGI) or after (Mac) version numbers
+#
+#  Revision 3.10  2003/09/25 00:04:08  mast
+#  Improve test for no entry in configure
+#
+#  Revision 3.9  2003/08/25 18:47:13  mast
+#  Have it make the install directory if needed, and delete existing links
+#
+#  Revision 3.8  2003/08/13 20:01:41  mast
+#  Have it use LIBEXT from configure if available, add test for libqt.la
+#
+#  Revision 3.7  2003/05/08 23:29:09  mast
+#  change for windows
+#
+#  Revision 3.6  2003/05/08 21:42:35  mast
+#  Get libqt name better
+#
+#  Revision 3.5  2003/05/08 20:58:43  mast
+#  Initial creation (deleted messages while thrashing
+#
+#
