Implemented options for specifying or skipping the script copying and for getting help; tested for existence of directories; handled relative script directory; tested for targeted security context and said error probably OK

diff --git a/dist/installIMOD b/dist/installIMOD
--- a/dist/installIMOD
+++ b/dist/installIMOD
@@ -5,27 +5,50 @@
 # If run with no package name, it will look for a package in the current 
 # directory and try to install it if there is only one.
 #
-#  $Author$
-#
-#  $Date$
-#
-#  $Revision$
+#  $Id$
 #
 #  Log at end of file
 
-# First check for install directory
+set installdir = ""
+set scriptdir = ""
+set custom = 0
+set skipcopy = 0
+
+echo In installIMOD: $*
+# First peel off any recognized arguments
+#
+while ($#argv > 0) 
+    switch ($argv[1])
+        case -d*:
+            set installdir = "$argv[2]"
+            shift; shift
+            breaksw
+        
+        case -sc*:
+            # Construct absolute path
+            set scriptdir = "$argv[2]"
+            set absolute = `echo $scriptdir | grep '^/'`
+            if ($status) set scriptdir = "`pwd`""/$scriptdir"
+            shift; shift
+            breaksw
+        
+        case -sk*:
+            set skipcopy = 1
+            shift
+            breaksw
+
+        case -h*:
+        case --help:
+            goto usage
+            breaksw
+
+        default:
+            break
+    endsw
+end
+
 # Set the package name from the argument and check it if there is one
 #
-set installdir = ""
-set custom = 0
-
-if ($#argv > 0) then
-    if ("$argv[1]" == "-d" || "$argv[1]" == "-dir") then
-        set installdir = $argv[2]
-        shift; shift
-    endif
-endif
-
 if ($#argv > 0) then
     set package = "$argv[1]"
     if (! -r "$package") then
@@ -118,9 +141,26 @@ endif
 
 set sysdir = /etc
 if ($os == linux || $os == windows) set sysdir = /etc/profile.d
+if ("$scriptdir" != "") set sysdir = "$scriptdir"
 
-if (! -w $installdir || ! -w $sysdir) then
-    echo "You do not have permission to write to both $installdir and $sysdir"
+if (! -d "$installdir") then
+    echo "The install directory $installdir does not exist or is not a directory"
+    exit 1
+endif
+
+if (! $skipcopy && ! -d "$sysdir") then
+    echo "The directory to copy scripts to, $sysdir, does not exist or is not a directory"
+    exit 1
+endif
+
+if (! -w "$installdir") then
+    echo "You do not have permission to write to $installdir"
+    echo  "Run this command with sudo or as root"
+    exit 1
+endif
+
+if (! $skipcopy && ! -w "$sysdir") then
+    echo "You do not have permission to write to $sysdir"
     echo  "Run this command with sudo or as root"
     exit 1
 endif
@@ -131,7 +171,7 @@ set packpath = ""
 set absolute = `echo $package | grep '^/'`
 if ($status) set packpath = "`pwd`""/"
 
-cd $installdir
+cd "$installdir"
 
 # If file exists as a link, just remove it
 #
@@ -221,13 +261,13 @@ if ($custom == 1) then
     end
 endif    
 
-if ($os == windows || $os == linux) then
+if (($os == windows || $os == linux || "$scriptdir" != "") && ! $skipcopy) then
 
-    # The easy ones: copy to /etc/profile.d
+    # The easy ones: copy to /etc/profile.d or designated place
     #
-    echo "Copying startup scripts to /etc/profile.d: $scripts"
-    \cp $scripts /etc/profile.d
-else
+    echo "Copying startup scripts to ${sysdir}: $scripts"
+    \cp $scripts "$sysdir"
+else if (! $skipcopy) then
 
     # The hard ones: append a source command to a system file if files exist
     # and it is not there already
@@ -279,8 +319,10 @@ if ($os == linux && -e /usr/sbin/sestatus) then
         echo "SELinux is enabled - Trying to change security context of libraries."
         chcon -t texrel_shlib_t lib/*.so pylib/*.so >& /dev/null
         if ($status) then
-            echo "Errors occurred changing the security context."
-            echo "Disable SELinux if you have permission problems running IMOD programs."
+            echo "  Errors occurred changing the security context."
+	    set test = `/usr/sbin/sestatus | sed -n '/Policy from .*targeted/p'`
+	    if ("$test" != "") echo "  This is probably OK since your policy is targeted."
+            echo "  Disable SELinux if you have permission problems running IMOD programs."
         endif
         if (-e qtlib) chcon -t texrel_shlib_t qtlib/*.so >& /dev/null
     endif
@@ -297,7 +339,7 @@ echo "IMOD-related files in $installdir :"
 cd ..
 ls -l | grep -i imod | grep -vi tempDir
 echo ""
-set oldlist = `\find . -type d -maxdepth 1 -name 'imod_*.*[0-9]' -print | sed -e '/^\.\//s///g' -e "/imod_$vernum/d"`
+set oldlist = `\find .  -maxdepth 1 -type d -name 'imod_*.*[0-9]' -print | sed -e '/^\.\//s///g' -e "/imod_$vernum/d"`
 if ("$oldlist" != "") then
     echo "Do you want to remove these other versions?"
     echo "    " $oldlist
@@ -310,8 +352,24 @@ echo "If there are version-specific IMOD startup commands in individual user"
 echo " startup files (.cshrc, .bashrc) they should be changed or removed."
 exit 0
 
+usage:
+cat <<EOF
+Usage: installIMOD [options] [package file name]
+  Installs IMOD using a package in the current directory if there is only one,
+    or using the specified package file.
+  Options (may be abbreviated):
+    -dir dir     Directory in which to install IMOD  (not available on Windows)
+    -script dir  Directory in which to place the IMOD startup scripts
+    -skip        Skip copying startup scripts or modifying system startup files
+    -h, --help   Print this help
+EOF
+exit 0
+
 #
 #  $Log$
+#  Revision 3.14  2007/07/19 15:45:35  mast
+#  Limited depth of search for IMOD versions
+#
 #  Revision 3.13  2006/11/10 22:39:43  mast
 #  Tried to change security contect of libs if selinux is on
 #
