Converted tiltxcorr to PIP input

diff --git a/scripts/copytomocoms b/scripts/copytomocoms
--- a/scripts/copytomocoms
+++ b/scripts/copytomocoms
@@ -601,6 +601,30 @@ while ($iaxis < $numax)
         endif
     endif
 
+    # Handle text for PIP-style tilt options
+
+
+    set incDelText = "TiltIncrement"
+    set tiltIncText = "gibberish232"
+    set tiltInc = 1
+    if ($tiltopt < 0) then
+        set tiltTypeText = "TiltAngles"
+    else if ($tiltopt == 0) then
+        set tiltTypeText = "TiltFile"
+    else
+        set tiltTypeText = "FirstTiltAngle"
+        set startInc = `echo $tiltspec | sed '/,/s// /g'`
+        if ($#startInc < 2) then
+            echo "ERROR: $pn - You entered only one number for start and increment tilt angles"
+            exit 1
+        endif
+        set tiltspec = $startInc[1]
+        set tiltInc = $startInc[2]
+        set tiltIncText = "TiltIncrement"
+        set incDelText = "gibberish434"
+    endif
+
+
     set excludelistin = ($excludelistin)
     set excludelist = ""
     while ($#excludelistin > 0)
@@ -670,9 +694,10 @@ EOF
 
         set srcfile = $srcdir/"xcorr"$srcext
         sed -e s/$srcname/$dstname/g\
-	    -e "/tilts: 1 for start/s/.*	/$tiltopt	/g"\
-	    -e "/start and increment if 1/s/^.*/$tiltspec/g"\
-	    -e "/rotation angle/s/.*	/$axisangle	/g"\
+	    -e "/^FirstTiltAngle/s/.*/$tiltTypeText	$tiltspec/"\
+	    -e "/^$tiltIncText/s/	.*/	$tiltInc/"\
+	    -e "/^$incDelText/d"\
+	    -e "/^RotationAngle/s/	.*/	$axisangle/"\
 	    -e s/$setname.st/$xcsrc/\
 	    <$srcfile >>$dstfile
 	echo '$'"if (-e $backupname) $backupname" >> $dstfile
@@ -1189,6 +1214,9 @@ exit 0
 
 #
 #  $Log$
+#  Revision 3.21  2004/02/23 22:49:58  mast
+#  Needed to escape any / characters in distortion filename
+#
 #  Revision 3.20  2004/01/28 00:28:11  mast
 #  Change from .fidxf to _fid.xf
 #
