Made it do multiple PIDs

diff --git a/scripts/imodkillgroup b/scripts/imodkillgroup
--- a/scripts/imodkillgroup
+++ b/scripts/imodkillgroup
@@ -1,14 +1,72 @@
 #!/bin/csh -f
 # A simple script to kill a process group given the PID of one member of the
-# group
+# group.  Given multiple PIDs it will kill all the groups with one ps command
 #
-#  $Author$
+#  $Id$
 #
-#  $Date$
+
+if ($#argv < 1) then
+    echo "ERROR: imodkillgroup - no PID provided as argument 1"
+    exit 1
+endif
+
+set system = `uname -s`
+
+# Get PID and PGID in two column output for each system, for all lines 
+# containing the PID somewhere
 #
-#  $Revision$
-#
+switch ($system)
+    case *IRIX*:
+        set proclist = `ps -ej | awk '{print $1, $2}'`
+        breaksw
+    case *Linux*:
+        set proclist = `ps -eo "%p %r"`
+        breaksw
+    case *CYGWIN*:
+
+        # Strip any leading characters like S for suspended
+        set proclist = `ps -el | sed -e '/^[^ ]/s///' | awk '{print $1, $3}'`
+        breaksw
+    case *Darwin*:
+        set proclist = `ps -jA | awk '{print $2, $4}'`
+        breaksw
+    default:
+        echo "ERROR: imodkillgroup - system $system not supported"
+        exit 2
+endsw
+
+set retval = 0
+while ($#argv > 0)
+    set pid = $argv[1]
+    shift
+
+    # Search for the PID and kill by the PGID
+    #
+    @ i = 0
+    set found = 0
+    while ($i < $#proclist - 1)
+        @ i++
+        if ("$proclist[$i]" == "$pid") then
+
+            # For some reason it didn't like $proclist[$i+1]; "missing -"
+            @ j = $i + 1
+            \kill -9 -$proclist[$j]
+            set found = 1
+            break
+        endif
+    end
+    if (! $found) then
+        echo "imodkillgroup - no process found with PID $pid"
+        set retval = 3
+    endif
+end
+
+exit $retval
+
 #  $Log$
+#  Revision 3.4  2010/11/02 16:38:07  mast
+#  remove DOS endings (?)
+#
 #  Revision 3.3  2010/11/02 16:35:01  mast
 #  Fix for cygwin killing suspended process
 #
@@ -18,47 +76,3 @@
 #  Revision 3.1  2005/08/24 16:04:38  mast
 #  Addition to package
 #
-#
-
-if ($#argv < 1) then
-    echo "ERROR: imodkillgroup - no PID provided as argument 1"
-    exit 1
-endif
-
-set pid = $argv[1]
-set system = `uname -s`
-
-# Get PID and PGID in two column output for each system, for all lines 
-# containing the PID somewhere
-#
-switch ($system)
-    case *IRIX*:
-        set proclist = `ps -ej | grep $pid | awk '{print $1, $2}'`
-        breaksw
-    case *Linux*:
-        set proclist = `ps -eo "%p %r" | grep $pid`
-        breaksw
-    case *CYGWIN*:
-
-        # Strip any leading characters like S for suspended
-        set proclist = `ps -el | sed -n -e '/^[^ ]/s///' -e "/$pid/p" | awk '{print $1, $3}'`
-        breaksw
-    case *Darwin*:
-        set proclist = `ps -jA | grep $pid | awk '{print $2, $4}'`
-        breaksw
-    default:
-        echo "ERROR: imodkillgroup - system $system not supported"
-        exit 2
-endsw
-
-# Search for the PID and kill by the PGID
-#
-while ($#proclist >= 2)
-    if ("$proclist[1]" == "$pid") then
-        \kill -9 -$proclist[2]
-        exit 0
-    endif
-    shift proclist ; shift proclist
-end
-echo "imodkillgroup - no process found with PID $pid"
-exit 3
