backport

diff --git a/scripts/processchunks b/scripts/processchunks
--- a/scripts/processchunks
+++ b/scripts/processchunks
@@ -222,12 +222,13 @@ else
     if ($#tenthoulist > 0) set comlist = ($comlist $tenthoulist)
 
     if (-e $endroot.com) set comlist = ($comlist $endroot.com)
+
+    if ($#hundlist < 1 && $#thoulist < 1 && $#tenthoulist < 1) then
+        echo "ERROR: $pn - There are no command files matching $rootname-nnn.com"
+        exit 1
+    endif
 endif
 
-if ($#comlist < 1) then
-    echo "ERROR: $pn - There are no command files matching $rootname-nnn.com"
-    exit 1
-endif
 
 set thishost = `hostname`
 set hostroot = $thishost:r:r:r
@@ -690,7 +691,7 @@ EOF
                 #
                 if ($runflag == -1 && ! $syncing) then
                     @ nextsync = $num
-                    set nochunks = 1
+                    if ($foundchunks == 0) set nochunks = 1
                     break
                 endif
                 if ($undone == -1 && $runflag != 2) @ undone = $num
@@ -703,8 +704,8 @@ EOF
                 # error, and not all machines have done so
                 #
                 set chunkok = 1
-                if ($numchunkerr[$num] > 0 && $chunkerred[$name] == 1 && \
-                    $chunkerrtot < $#machines) then
+                if ($runflag <= 0 && $numchunkerr[$num] > 0 && \
+                    $chunkerred[$name] == 1 && $chunkerrtot < $#machines) then
                     set chunkok = 0
                     if ($syncing) break
                 endif
@@ -764,6 +765,7 @@ EOF
 
         # Set syncing flag to 1 to get it started
         set syncing = 1
+        @ firstundone = $nextsync
         @ nextsync = $#comlist + 2
         set nochunks = 0
     endif
@@ -935,6 +937,12 @@ exit 2
 
 #
 #  $Log$
+#  Revision 3.55  2010/08/31 18:36:10  mast
+#  Fixed two problems with hanging due to nochunks being set erroneously
+#
+#  Revision 3.54  2010/08/19 01:48:24  mast
+#  Fixed test for no numbered com files
+#
 #  Revision 3.53  2010/06/14 20:42:37  mast
 #  Copy log from first non-sync chunk if any; report WARNINGS
 #
