Added ability to run with sync files

diff --git a/scripts/processchunks b/scripts/processchunks
--- a/scripts/processchunks
+++ b/scripts/processchunks
@@ -8,6 +8,9 @@
 #  $Revision$
 #
 #  $Log$
+#  Revision 3.5  2004/08/27 05:46:48  mast
+#  Switched to using head -n and tail -n
+#
 #  Revision 3.4  2004/07/23 00:09:00  mast
 #  Set default nice to 18 per user request
 #
@@ -148,7 +151,10 @@ set flags = ()
 @ num = 0
 while ($num < $#comlist)
     @ num++
-    set flags = ($flags 0)
+    set sync = 0
+    set test = `echo $comlist[$num] | grep -i '[0-9]-sync.com'`
+    if (! $status) set sync = -1
+    set flags = ($flags $sync)
 end
 
 set assigned = ()
@@ -168,6 +174,10 @@ if ($retain == 0) then
     if (-e $rootname-start.com) then
         echo "Going to run $rootname-start first..."
         vmstocsh $rootname-start.log < $rootname-start.com | csh -ef
+        if ($status) then
+            echo "Error running $rootname-start.com, check $rootname-start.log"
+            exit 1
+        endif
     endif
 else
 
@@ -193,6 +203,7 @@ onintr report
 #
 @ lastdone = 0
 @ count = 0
+@ nextsync = $#comlist + 2
 
 continue:
 
@@ -251,6 +262,13 @@ while ($numdone < $#comlist)
         @ num = 0
         while ($num < $#comlist && $assigned[$proc] == 0 && $dropout == 0)
             @ num++
+
+            # But if the next com is a sync, record number and break loop
+            #
+            if ($flags[$num] == -1) then
+                @ nextsync = $num
+                break
+            endif
             if ($flags[$num] == 0) then
                 set assigned[$proc] = $num
                 set flags[$num] = 1
@@ -275,6 +293,21 @@ while ($numdone < $#comlist)
 
     if ($numdone > $lastdone) echo $numdone DONE SO FAR
     @ lastdone = $numdone
+
+    # If we have finished up to the sync file, then run it
+    if ($numdone >= $nextsync - 1) then
+        set comname = $comlist[$nextsync]
+        set logname = $comname:r.log
+        echo "Running $comname to synchronize ..."
+        vmstocsh $logname < $comname | csh -ef
+        if ($status) then
+            echo "Error running $comname, check $logname"
+            exit 1
+        endif
+        set flags[$nextsync] = 1
+        @ nextsync = $#comlist + 2
+        @ numdone++
+    endif
 end
 
 echo "ALL DONE - going to run $rootname-finish to reassemble"
