Made start, sync, and finish all run asynchronously on first machine; they are now killable, and resume will treat start and finish properly. Backed up logs of undone chunks on fresh start.

diff --git a/scripts/processchunks b/scripts/processchunks
--- a/scripts/processchunks
+++ b/scripts/processchunks
@@ -160,15 +160,23 @@ endif
 
 # Build up lists in order -nnn, -nnnn, -nnnnn*, which should work both for
 # lists that are all 5 digits or lists that are 3, 4, 5 digits
+# Put -start.com on front and -finish.com on end
 #
 set rootname = $argv[2]
-set comlist = `\find . -name "$rootname-[0-9][0-9][0-9][^0-9]*com" -print | sed '/\.\//s///' | sort`
+set endroot = $rootname-finish
+set comlist = ()
+if (-e $rootname-start.com) set comlist = ($rootname-start.com)
 
-set thoulist = `\find . -name "$rootname-[0-9][0-9][0-9][0-9][^0-9]*com" -print | sed '/\.\//s///' | sort`
+set hundlist = `\find . -maxdepth 1 -name "$rootname-[0-9][0-9][0-9][^0-9]*com" -print | sed '/\.\//s///' | sort`
+if ($#hundlist > 0) set comlist = ($comlist $hundlist)
+
+set thoulist = `\find . -maxdepth 1 -name "$rootname-[0-9][0-9][0-9][0-9][^0-9]*com" -print | sed '/\.\//s///' | sort`
 if ($#thoulist > 0) set comlist = ($comlist $thoulist)
 
-set tenthoulist = `\find . -name "$rootname-[0-9][0-9][0-9][0-9][0-9]*com" -print | sed '/\.\//s///' | sort`
+set tenthoulist = `\find . -maxdepth 1 -name "$rootname-[0-9][0-9][0-9][0-9][0-9]*com" -print | sed '/\.\//s///' | sort`
 if ($#tenthoulist > 0) set comlist = ($comlist $tenthoulist)
+
+if (-e $endroot.com) set comlist = ($comlist $endroot.com)
 
 if ($#comlist < 1) then
     echo "ERROR: $pn - There are no command files matching $rootname-nnn.com"
@@ -244,8 +252,11 @@ set numchunkerr = ()
 while ($num < $#comlist)
     @ num++
     set sync = 0
-    set test = `echo $comlist[$num] | grep -i '[0-9]-sync.com'`
-    if (! $status) set sync = -1
+    set comname = $comlist[$num]
+#    set test = `echo $comlist[$num] | grep -i '[0-9]-sync.com'`
+#    if (! $status) set sync = -1
+    if ($comname =~ *-start.com || $comname =~ *-finish.com || \
+        $comname =~ *-sync.com ) set sync = -1
     set flags = ($flags $sync)
     set numchunkerr = ($numchunkerr 0)
 end
@@ -288,50 +299,45 @@ end
 # Quoting the assignments did not always work
 set noglob
 
-# remove logs if not restarting, and run starting file
+# Prescan logs for done ones to find first undone one, or back up unfinished
 #
 @ numdone = 0
 @ firstundone = -1
-if ($retain == 0) then
-    \find . -type f -name  "$rootname-[0-9]*.log" -exec rm -f "{}" \;
-    set startroot = $rootname-start
-    if (-e $startroot.com) then
-        echo "Going to run $startroot first..."
-        vmstocsh $startroot.log < $startroot.com >! $startroot.csh
-        if ($queue) then
-            $queuecom -w "$curdir" -a S $startroot
-            set retval = $status
-        else
-            csh -ef $startroot.csh
-            set retval = $status
-        endif
-        \rm -f $startroot.csh
-        if ($retval) then
-            echo "ERROR: RUNNING $startroot.com, FROM $startroot.log:"
-            sed -n '/.*ERROR:/s//ERROR:/p' $startroot.log
-            exit 1
-        endif
-    endif
-else
-
-    # otherwise prescan logs for done ones
-    #
-    @ num = 0
-    while ($num < $#comlist)
-        @ num++
-        set logname = $comlist[$num]:r.log
-        if (-e $logname) then
-            set lastline = `tail -n 1 $logname | sed '/[[:cntrl:]]/s///g'`
-            if ("$lastline" == "CHUNK DONE") then
+@ num = 0
+while ($num < $#comlist)
+    @ num++
+    set logname = $comlist[$num]:r.log
+    if (-e $logname) then
+        set lastline = `tail -n 1 $logname | sed '/[[:cntrl:]]/s///g'`
+        if ("$lastline" == "CHUNK DONE") then
+        
+            # If it was done and we are resuming, set flag it is done, count
+            if ($retain) then
                 set flags[$num] = 2
                 @ numdone++
             endif
+        else if ($retain == 0) then
+
+            # If it was not done and we are restarting, back up the old log
+            #
+            \mv $logname $logname~
         endif
-        if ($firstundone == -1 && $flags[$num] != 2) @ firstundone = $num
-    end 
-endif
+    endif
+
+    # If resuming and this is the first undone one, keep track of that
+    #
+    if ($retain && $firstundone == -1 && $flags[$num] != 2) \
+        @ firstundone = $num
+end 
 if ($firstundone == -1) @ firstundone = 1
 
+# remove logs if not restarting
+#
+if ($retain == 0) then
+    \find . -type f -name  "$rootname-[0-9]*.log" -exec rm -f "{}" \;
+    \find . -type f -name  "$rootname-start.log" -exec rm -f "{}" \;
+    \find . -type f -name  "$endroot.log" -exec rm -f "{}" \;
+endif
 
 # Clean up .ssh and .pid files to avoid confusion
 #
@@ -350,6 +356,7 @@ set anydone = 0
 @ holdcrit = ($#machines + 1) / 2
 set pausing = 0
 @ checkline = 0
+set syncing = 0
 
 continue:
 
@@ -446,6 +453,7 @@ while ($numdone < $#comlist)
                     set flags[$ind] = 2
                     set assigned[$proc] = 0
                     set failed[$name] = 0
+                    set syncing = 0
                     if ($numchunkerr[$ind] != 0) set chunkerred[$name] = 0
                     @ numdone++
                     echo "$comlist[$ind] finished on $machines[$proc]"
@@ -492,11 +500,17 @@ EOF
                         @ numerr++
                         set numchunkerr[$ind] = $numerr
                         set chunkerred[$name] = 1
-                        if ($numerr >= $maxchunkerr) then
+
+                        # Give up if the chunk errored too many times: and
+                        # for a sync chunk that is twice or once if one machine
+                        #
+                        if ($numerr >= $maxchunkerr || ($syncing && \
+                            ($#namelist == 1 || $numerr >= 2))) then
                             echo \
         "$comlist[$ind] has given processing error $numerr times - giving up"
                             echo "$errormess"
                             set ans = "E"
+                            set assigned[$proc] = 0
                             goto command
                         endif
                     else if (! $queue && -e $pidname) then
@@ -573,6 +587,8 @@ EOF
                 echo "$comlist[$ind] failed on $machines[$proc] - need to restart"
                 if ("$errormess" != "") echo "$errormess"
                 set flags[$ind] = 0
+                if ($syncing) set flags[$ind] = -1
+                if ($syncing) set syncing = 1
                 set assigned[$proc] = 0
                 set nochunks = 0
                 @ failcount = $failed[$name]
@@ -608,33 +624,38 @@ EOF
         # Move current log out of way so non-existence of log can be sign of
         # nothing having started.  Skip if no chunks are available
         #
-        if ($assigned[$proc] == 0 && $dropout == 0 && $nochunks == 0) then
+        if ($assigned[$proc] == 0 && $dropout == 0 && $nochunks == 0 && \
+                $syncing != 2) then
             @ num = $firstundone
             set foundchunks = 0
             @ undone = -1
             while ($num <= $#comlist && $assigned[$proc] == 0)
+                @ runflag = $flags[$num]
 
                 # But if the next com is a sync, record number and break loop
                 #
-                if ($flags[$num] == -1) then
+                if ($runflag == -1 && ! $syncing) then
                     @ nextsync = $num
                     set nochunks = 1
                     break
                 endif
-                if ($undone == -1 && $flags[$num] != 2) @ undone = $num
+                if ($undone == -1 && $runflag != 2) @ undone = $num
 
                 # If any chunks found set that flag
                 #
-                if ($flags[$num] == 0) set foundchunks = 1
+                if ($runflag <= 0) set foundchunks = 1
 
                 # Skip a chunk if it has errored, if this machine has given chunk 
                 # error, and not all machines have done so
                 #
                 set chunkok = 1
                 if ($numchunkerr[$num] > 0 && $chunkerred[$name] == 1 && \
-                    $chunkerrtot < $#machines) set chunkok = 0
+                    $chunkerrtot < $#machines) then
+                    set chunkok = 0
+                    if ($syncing) break
+                endif
 
-                if ($flags[$num] == 0 && $chunkok == 1) then
+                if ($runflag <= 0 && $chunkok == 1) then
                     set assigned[$proc] = $num
                     set flags[$num] = 1
                     set startcount[$proc] = $count
@@ -653,6 +674,15 @@ EOF
                         \echo "nice +$nice" >! $cshname
                     endif
                     vmstocsh $logname < $comname >> $cshname
+
+                    # If running a sync, set the syncing flag to 2 and add
+                    # a CHUNK DONE to -start or -finish files
+                    #
+                    if ($syncing) then
+                        set syncing = 2
+                        if ($comname !~ *sync.com) \
+                            echo "echo CHUNK DONE > $logname" >> $cshname
+                    endif
                     if ($queue) then
                         $queuecom -w "$curdir" -a R $comname:r
                     else if ("$machname" == $hostroot || "$machname" == localhost) then
@@ -674,65 +704,23 @@ EOF
     if ($numdone > $lastdone) echo $numdone OF $#comlist DONE SO FAR
     @ lastdone = $numdone
 
-    # If we have finished up to the sync file, then run it
+    # If we have finished up to the sync file, then allow the loop to run it
     if ($numdone >= $nextsync - 1) then
-        set comname = $comlist[$nextsync]
-        set logname = $comname:r.log
-        set cshname = $comname:r.csh
-        vmstocsh $logname < $comname >! $cshname
-        echo "Running $comname to synchronize ..."
-        if ($queue) then
-            $queuecom -w "$curdir" -a S $comname:r
-            set retval = $status
-        else
-            csh -ef $cshname
-            set retval = $status
-        endif
-        \rm -f $cshname
-        if ($retval) then
-            echo "ERROR: RUNNING $comname, FROM ${logname}:"
-            set errormess = `sed -n '/.*ERROR:/s//ERROR:/p' $logname`
-            if ("$errormess" == "") then
-                set errormess = `sed '/^ *$/d' $logname | tail -n 1`
-                set errormess = "ERROR: (last line) - $errormess"
-            endif
-            echo "$errormess"
-            exit 1
-        endif
-        echo "$comname finished on $hostroot"
-        set flags[$nextsync] = 2
+        if ($comlist[$nextsync] == $endroot.com) \
+            echo "ALL DONE - going to run $endroot to reassemble"
+
+        # Set syncing flag to 1 to get it started
+        set syncing = 1
         @ nextsync = $#comlist + 2
-        @ numdone++
         set nochunks = 0
     endif
 
     sleep $sleepsec
 end
 
-onintr finishkilled
-set endroot = $rootname-finish
-if (-e "$endroot.com") then
-    echo "ALL DONE - going to run $endroot to reassemble"
-    vmstocsh $endroot.log < $endroot.com >! $endroot.csh
-    if ($queue) then
-        $queuecom -w "$curdir" -a S $endroot
-        set retval = $status
-    else
-        csh -ef $endroot.csh
-        set retval = $status
-    endif
-    \rm -f $endroot.csh
-    if ($retval) then
-        echo "ERROR: RUNNING $endroot.com, FROM $endroot.log:"
-        sed -n '/.*ERROR:/s//ERROR:/p' $endroot.log
-        exit 1
-    endif
-else
-
-    # Etomo is looking for "to reassemble"
-    #
-    echo "ALL DONE - nothing to reassemble"
-endif
+# Etomo is looking for "to reassemble"
+#
+if (! -e "$endroot.com") echo "ALL DONE - nothing to reassemble"
 
 # Etomo is looking for this line too
 #
@@ -874,7 +862,8 @@ while ($ind < $#pidkills)
 end
 
 if ("$ans" == "E") then
-    echo "ERROR: A CHUNK HAS FAILED $maxchunkerr TIMES"
+    if (! $syncing) echo "ERROR: A CHUNK HAS FAILED $maxchunkerr TIMES"
+    if ($syncing) echo "ERROR: A START, FINISH, OR SYNC CHUNK HAS FAILED"
     exit 4
 endif
 
@@ -890,14 +879,12 @@ echo "When you rerun with a different set of machines, be sure to use"
 echo "the -r flag to retain the existing results"
 exit 2
 
-finishkilled:
-echo ""
-echo "$rootname-finish was interrupted and the data have not been reassembled."
-echo "Rerun with -r or use subm $rootname-finish to reassemble."
-exit 3
 
 #
 #  $Log$
+#  Revision 3.47  2009/08/04 22:41:08  mast
+#  Move the noglob up so it works when scanning existing logs
+#
 #  Revision 3.46  2009/05/26 18:37:12  mast
 #  Ignore error lines when getting version string
 #
