Modified to use new parallel write stuff

diff --git a/scripts/splitcorrection b/scripts/splitcorrection
--- a/scripts/splitcorrection
+++ b/scripts/splitcorrection
@@ -10,6 +10,7 @@ set pn = splitblend
 @ maxslices = 5
 @ targetratio = 4
 @ targetslabs = 0
+@ boundpixels = 2048
 
 if ($#argv < 1) then
 cat <<EOF
@@ -17,11 +18,13 @@ Usage: $pn [options] command_file
    Produces multiple command files for running 'ctfphaseflip' in parallel.
    Options:
       -m #   Maximum number of slices to be corrected per chunk (default $maxslices)
+      -b #   Number of boundary pixels for direct writing (default $boundpixels)
 EOF
 exit 0
 endif
 
 setenv LC_NUMERIC C
+set boundext = cbound
 
 if ($?IMOD_DIR) then
     setenv PATH "$IMOD_DIR/bin:$PATH"
@@ -35,6 +38,11 @@ while ($#argv > 1)
       @ maxslices = $argv[2]
       shift; shift
       breaksw
+    case -b:
+      @ boundpixels = $argv[2]
+      shift; shift
+      breaksw
+
     default:
       echo "ERROR: $pn - unrecognized option $argv[1]"
       exit 1
@@ -50,10 +58,6 @@ if (! -e $comname) then
     exit 1
 endif
 
-# Set target slabs if not entered
-#
-if ($targetslabs == 0) @ targetslabs = $targetratio * $numproc
-
 # Get name of output file
 set outline = `sed -n -e '/	/s// /g' -e '/[[:cntrl:]]/s///g' -e '/^ *OutputF/p' $comname`
 if ($#outline < 2) then
@@ -66,14 +70,22 @@ set outfile = $outline[2]
 \rm -f $rootname-start.com $rootname-finish.com
 
 set views = `grep -i StartingEndingViews $comname | grep -v '^#' | sed '/[^ 0-9\.]/s///g'`
-set inStack = `grep -i InputStack $comname | grep -v '^#'` 
+set inStack = `grep -i InputStack $comname | grep -v '^#' | sed '/[[:cntrl:]]/s///g'` 
+set dimensions = `header -s $inStack[2] | sed '/[[:cntrl:]]/s///g'`
+if (! -e $inStack[2]) then
+    echo "ERROR: $pn - Input stack $inStack[2] does not exist"
+    exit 1
+endif
 if ($#views <2 ) then
-   set dimensions = `header -s $inStack[2] | sed '/[[:cntrl:]]/s///g'`
    set views = `echo "1  $dimensions[3]"`
 endif
 
 set viewdel = 'StartingEndingViews'
 @ total = 1 + $views[2] - $views[1]
+
+@ numslabs = ($total + $maxslices - 1) / $maxslices
+@ slabsize = $total / $numslabs
+@ remainder = $total - $numslabs * $slabsize
 
 set outroot = $outfile:r
 set outext = $outfile:e
@@ -97,11 +109,18 @@ TotalViews $views[1] $views[2]\
 EOF
 endif
 
-@ num = 0
-set currSlice = 0
-set origOffset = $views[1]
+set boundfile = $rootname-bound.info
+@ width = $dimensions[1]
+@ boundlines = ($boundpixels + $width - 1) / $width
+@ ny = $dimensions[2]
+if ($boundlines > $ny / 2 + 1) @ boundlines =  $ny / 2 + 1
+echo "1 0 $width $boundlines $numslabs" >! $boundfile
 
-while ($currSlice < $total)
+@ num = 0
+set origOffset = $views[1]
+@ firstview = $views[1]
+
+while ($num < $numslabs)
     @ num++
     set numtext = $num
     if ($num < 10) then
@@ -111,13 +130,8 @@ while ($currSlice < $total)
     endif
     set thiscom = $rootname-$numtext.com
 
-    @ currSlice = $currSlice + $maxslices
-
-    if ($currSlice > $total ) then
-        set origEnd = $views[2]
-    else
-        @ origEnd = $origOffset + $maxslices - 1 
-    endif
+    @ origEnd = $origOffset + $slabsize - 1 
+    if ($num <= $remainder) @ origEnd++
 
     sed -e "/$viewdel/d" \
         -e "/DefocusFile/a\\
@@ -126,18 +140,33 @@ $viewdel $origOffset  $origEnd\
         -e "/DefocusFile/a\\
 TotalViews $views[1] $views[2]\
 " \
+        -e "/DefocusFile/a\\
+BoundaryInfoFile $boundfile\
+" \
   $comname >! $thiscom
     cat <<EOF >> $thiscom
 \$echo CHUNK DONE
 EOF
-   @ origOffset =$origOffset + $maxslices
+
+   @ boundstart = $origOffset - $firstview
+   @ boundend = $origEnd - $firstview
+   if ($num == 1) @ boundstart = -1
+   if ($num == $numslabs) @ boundend = -1
+   echo $outroot-$numtext.$boundext >> $boundfile
+   echo "$boundstart 0 $boundend -1" >> $boundfile
+
+   @ origOffset = $origEnd + 1
 end
 
 set finish = $rootname-finish.com
    cat <<EOF >! $finish
+\$fixboundaries $outfile $boundfile
 \$collectmmm pixels= $rootname $num $outline[2]
-\$\\rm -f $rootname-[0-9]*.* $rootname-start*.* $rootname-finish*.* 
+\$\\rm -f $rootname-[0-9]*.* $rootname-start*.* $rootname-finish*.* $outroot-[0-9]*.$boundext $boundfile
 EOF
 
 #  $Log$
+#  Revision 3.3  2007/11/06 23:31:45  xiongq
+#  add log funtion and use DefocusFile option
+#
 #
diff --git a/scripts/splittilt b/scripts/splittilt
--- a/scripts/splittilt
+++ b/scripts/splittilt
@@ -14,6 +14,7 @@ set penalty = 1.33
 @ minslices = 50
 @ minratio = 2
 @ targetratio = 5
+@ boundpixels = 2048
 
 if ($#argv < 1) then
 cat <<EOF
@@ -28,6 +29,7 @@ Usage: $pn [options] command_file
       -v     Do vertical slices instead of old-style X-axis tilting
       -f     Allow fast backprojection where possible
       -c     Write chunks to separate files, not directly to single output file
+      -b #   Number of boundary pixels for direct writing (default $boundpixels)
       -i #   Set initial command file number to #
       -o     Leave command set open, finish with -sync instead of -finish
 EOF
@@ -48,6 +50,7 @@ set reproj = 0
 set ifstartnum = 0
 set leaveopen = 0
 @ startnum = 1
+set boundext = rbound
 
 while ($#argv > 1)
   switch ($argv[1])
@@ -89,6 +92,11 @@ while ($#argv > 1)
     case -c:
       set direct = 0
       shift
+      breaksw
+
+    case -b:
+      @ boundpixels = $argv[2]
+      shift; shift
       breaksw
 
     case -i:
@@ -133,7 +141,7 @@ set alifile = `grep -i inputproj $comname | grep -v '^#' | sed '/[^ 0-9\.]/s///g
 set recfile = `grep -i outputfile $comname | grep -v '^#' | sed '/[^ 0-9\.]/s///g'`
 set rectoproj = `grep -i recfiletoreproj $comname | grep -v '^#' | sed '/[^ 0-9\.]/s///g'`
 set sliceproj = `grep -i "^ *reproject" $comname`
-
+set width = `grep -i width $comname | grep -v '^#' | sed '/[^ 0-9\.]/s///g'`
 
 # Get the input image file name from the command file if necessary
 #
@@ -155,6 +163,11 @@ endif
 
 if (! -e $alifile && $#fullimage == 0 && "$slices" == "") then
     echo "ERROR: $pn - Command file has neither a SLICE nor a FULLIMAGE entry and image file does not exist yet"
+    exit 1
+endif
+
+if ($direct && (! -e $alifile) && $#fullimage == 0 && "$width" == "") then
+    echo "ERROR: $pn - Command file has neither a WIDTH nor a FULLIMAGE entry and image file does not exist yet"
     exit 1
 endif
 
@@ -284,6 +297,23 @@ endif
 @ slabsize = $numslices / $numslabs
 @ remainder = $numslices - $numslabs * $slabsize
 
+# Now that slab size is known, get binned width and # of bound lines
+#
+if ("$width" != "") then
+    @ widthnum = $width
+else
+    @ widthnum = $fullimage[1]
+endif
+@ widthnum /= $binning
+@ boundlines = ($boundpixels + $widthnum - 1) / $widthnum
+if ($reproj) then
+    if ($boundlines > $slabsize / 2 + 1) @ boundlines = $slabsize / 2 + 1
+else if ($slabsize == 1) then
+    if ($boundlines > $thickness / 2 + 1) @ boundlines = $thickness / 2 + 1
+else
+    if ($boundlines > $thickness - 1) @ boundlines = $thickness - 1
+endif
+
 set donetext = '$echo CHUNK DONE'
 set recroot = $recfile:r
 set templist = ()
@@ -291,9 +321,12 @@ set recsed = $recfile
 @ mintotslice = $binval * $firstslice
 @ maxtotslice = $binval * ($firstslice + $numslices - 1)
 set totsed = gibberish
+set boundsed = gibberish
+set boundfile = $rootname-bound.info
 if ($direct) then
     set totsed = THICKNESS
     set recsed = gibberish
+    set boundsed = THICKNESS
     set thiscom = $rootname-start.com
     if ($startnum > 1) then
         set numtext = `echo $startnum | awk '{printf "%03d\n", $1}'`
@@ -313,10 +346,12 @@ TOTALSLICES $mintotslice $maxtotslice\
     cat <<EOF >> $thiscom
 \$sync
 EOF
-if ($startnum > 1) echo "$donetext" >> $thiscom
+    if ($startnum > 1) echo "$donetext" >> $thiscom
+    echo "1 $reproj $widthnum $boundlines $numslabs" >! $boundfile
 endif
 
 @ num = 0
+@ firstofall = $firstslice
 while ($num < $numslabs)
     @ num++
     @ numrec = $num + $startnum - 1
@@ -351,11 +386,27 @@ $oldstyle\
         -e "/$totsed/a\\
 TOTALSLICES $mintotslice $maxtotslice\
 " \
+        -e "/$boundsed/a\\
+BoundaryInfoFile $boundfile\
+" \
         -e "/THICKNESS/a\\
 $nofbp\
 " $comname >> $thiscom
     echo "$donetext" >> $thiscom
 
+    if ($direct) then
+        echo "$recroot-$numtext.$boundext" >> $boundfile
+        @ boundstart = $firstslice - $firstofall
+        @ boundend = $lastslice - $firstofall
+        if ($reproj) @ boundend -= $boundlines - 1
+        if ($num == 1) @ boundstart = -1
+        if ($num == $numslabs) @ boundend = -1
+        if ($reproj) then
+            echo "-1 $boundstart -1 $boundend" >> $boundfile
+        else
+            echo "$boundstart 0 $boundend -1" >> $boundfile
+        endif
+    endif
     @ firstslice = $lastslice + 1
 end
 
@@ -400,8 +451,9 @@ EOF
     \echo "$cleanup $recroot-[0-9]*.$recext" >> $finish
 else
     cat <<EOF >! $finish
+\$fixboundaries $recfile $boundfile
 \$collectmmm pixels= $rootname $numslabs $recfile $startnum
-$cleanup
+$cleanup $recroot-[0-9]*.$boundext $boundfile
 EOF
 endif
 if ($leaveopen) echo "$donetext" >> $finish
@@ -410,6 +462,9 @@ echo "Command files for $numslabs chunks created and ready to run with:"
 echo "  processchunks machine_list $rootname"
 
 #  $Log$
+#  Revision 3.13  2008/07/31 16:44:09  mast
+#  Remove continuation inside back-ticks: tcsh allows, csh does not
+#
 #  Revision 3.12  2008/04/14 17:56:24  mast
 #  Used escaped echo to output escaped rm due to bad cygwin tcsh echo
 #
