Switched to using PIP input to matchvol, added linear interpolation option, and made it adjust pixel size

diff --git a/scripts/squeezevol b/scripts/squeezevol
--- a/scripts/squeezevol
+++ b/scripts/squeezevol
@@ -7,11 +7,15 @@
 #  $Revision$
 #
 #  $Log$
+#  Revision 3.1  2002/08/21 15:08:07  mast
+#  Suppressed confusing output from matchvol
+#
 
 
 set pn = "squeezevol"
 set factor = 1.6
 set tempdir = ""
+set linear = ""
 
 if ($#argv == 0)then
   echo "Usage: $pn [options] input_file output_file"
@@ -24,7 +28,7 @@ if ($#argv == 0)then
   echo "    -ix x_size :  input size in X dimension, default is full X size of volume"
   echo "    -iy y_size :  input size in Y dimension, default is full Y size of volume"
   echo "    -iz z_size :  input size in Z dimension, default is full Z size of volume"
-  echo "    -t tempdir :  path name of directory for temporary files"  
+  echo "    -l         :  use linear interpolation; default is quadratic"  
   exit 0
 endif
 
@@ -60,8 +64,12 @@ while ($#argv > 2)
       set factor = $argv[2]
       shift; shift
       breaksw
+    case -l*:
+      set linear = "InterpolationOrder 1"
+      shift
+      breaksw
     case -t*:
-      set tempdir = $argv[2]
+      set tempdir = "TemporaryDirectory $argv[2]"
       shift; shift
       breaksw
     default:
@@ -82,6 +90,9 @@ set nxyz =  `header $argv[1] | sed -n '/rows, sections/p'| awk '{print $7, $8, $
 if (! ${?ix}) set ix = $nxyz[1]
 if (! ${?iy}) set iy = $nxyz[2]
 if (! ${?iz}) set iz = $nxyz[3]
+set pixelxyz =  `header $argv[1] | sed -n '/Pixel spacing/p'| awk '{print $4, $5, $6}'`
+
+if ($#pixelxyz < 3) set pixelxyz = (1. 1. 1.)
 
 set ox = `echo $ix $xs | awk '{print 2 * int($1 * 0.5 / $2) }'`
 set oy = `echo $iy $ys | awk '{print int($1 / $2) }'`
@@ -91,17 +102,37 @@ set squeezex = `echo $xs | awk '{print 1. / $1}'`
 set squeezey = `echo $ys | awk '{print 1. / $1}'`
 set squeezez = `echo $zs | awk '{print 1. / $1}'`
 
+set pixelx = `echo $xs $pixelxyz[1] | awk '{printf "%.3f", $1 * $2}'`
+set pixely = `echo $ys $pixelxyz[2] | awk '{printf "%.3f", $1 * $2}'`
+set pixelz = `echo $zs $pixelxyz[3] | awk '{printf "%.3f", $1 * $2}'`
+
 echo "Squeezing the volume with matchvol..."
 
-matchvol <<HERESTRING | tail -1
-$argv[1]
-$argv[2]
+matchvol -StandardInput <<HERESTRING | tail -1
+InputFile $argv[1]
+OutputFile $argv[2]
 $tempdir
-$ox $oy $oz
-1
-
-$squeezex 0 0 0
-0 $squeezey 0 0
-0 0 $squeezez 0
-
+$linear
+OutputSizeXYZ $ox $oy $oz
+3DTransform $squeezex 0 0 0 0 $squeezey 0 0 0 0 $squeezez 0
 HERESTRING
+
+if ($status) then
+    echo "Error transforming volume"
+    exit 1
+endif
+
+echo "Adjusting pixel spacing in header to $pixelx $pixely $pixelz"
+echo " "
+alterheader <<EOF > /dev/null
+$argv[2]
+del
+$pixelx $pixely $pixelz
+done
+EOF
+
+if ($status) then
+    echo "Error runing alterheader"
+    exit 1
+endif
+
